[package]
name = "disc-grpc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.1", features = ["full"] }
tonic = "0.8.1"
tracing = "0.1.36"

[build-dependencies]
tonic-build = "0.8.0"
